default_platform :ios

platform :ios do
  desc "Upload application to TestFlight"
  before_all do
    setup_circle_ci
  end

  lane :beta do
    match(type: "appstore")
    sh('cd ../ && flutter build ios --config-only --no-codesign')
    build_app(scheme: "Runner")
    upload_to_testflight(is_key_content_base64: true)
  end
end

