name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  RELEASE_KEY_ALIAS: mock_alias
  RELEASE_KEY_PASSWORD: password
  RELEASE_STORE_PASSWORD: password

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore android/keystore -alias $RELEASE_KEY_ALIAS \
          -keyalg RSA -keysize 2048 -validity 10000 -storepass $RELEASE_STORE_PASSWORD \
          -keypass $RELEASE_KEY_PASSWORD -dname "cn=Unknown, ou=Unknown, o=Unknown, c=Unknown"
      - name:
        run: |
          printf "
          keyAlias=%s
          keyPassword=%s
          storeFile=%s
          storePassword=%s
          " $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD "$(pwd)/android/keystore" $RELEASE_STORE_PASSWORD > android/key.properties
      - run: flutter build apk
